### ISSUE TITLE
Feature - estimated time

### ISSUE THREAD

**Issue by AdamVerner** [Anagmate/kybersoutezTaskView#2]
predstavuju si to jako nejaky slider, popř zapisovac pole, do ktereho vlozim odhadovany cas tasku a podle toho by se postupne menila barva, jako to je ted.

2. level bylo "taskbar" pod jmenem, kterej by se postupne zaplnoval az do 100%

**Comment by Anagmate** [comment]
v zasade jde teda o to, ze chces menit, jak pomalu bude ta bunka s casem prechazet do cervene, protoze ne vsechny ukoly maji srovnatelna ocekavani, chapu to spravne?

**Comment by AdamVerner** [comment]
přesně tak

**Comment by AdamVerner** [comment]
jde mi o adaptibilitu

**Comment by Anagmate** [comment]
added in https://github.com/Anagmate/kybersoutezTaskView/commit/cd653d36534e7b18e23c0dee7fb40bbec2a0c71c -> closed
